imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    firewalls:
        secured:
            http_basic:

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%adminpass%", roles: [ 'ROLE_ADMIN' ] }

doctrine:
    dbal:
        driver: pdo_mysql
        host: "127.0.0.1"
        port: ~
        dbname: "f43_test"
        user: "root"
        password: ~
        charset: utf8mb4
