security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%adminpass%", roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        test:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern: ^/
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
            logout: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/feed/test, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/(feed)|(logs)|(item)|(dashboard)|(login_check), roles: ROLE_ADMIN }
