imports:
    - { resource: services/extractors.yml }
    - { resource: services/improvers.yml }
    - { resource: services/converters.yml }
    - { resource: services/parsers.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # autowire
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,DataFixtures,Converter,DomDocument,Extractor,Improver,Parser}'

    AppBundle\Xml\Render:
        arguments:
            $generator: "%domain%"

    AppBundle\Command\FetchItemsCommand:
        tags: ['console.command']
        arguments:
            $domain: "%domain%"

    AppBundle\Command\RemoveItemsCommand:
        tags: ['console.command']

    AppBundle\Consumer\FetchItems:
        arguments:
            $domain: "%domain%"

    AppBundle\EventListener\ItemSubscriber:
        arguments:
            $hub: "http://pubsubhubbub.appspot.com"
        tags:
            - { name: kernel.event_listener, event: app.after_item_cached, method: pingHub }

    AppBundle\EventListener\FeedSubscriber:
        tags:
            - { name: kernel.event_listener, event: app.after_feed_creation, method: sync }

    AppBundle\Xml\SimplePieProxy:
        arguments:
            $cache: "%kernel.root_dir%/cache/simplepie/"
            $itemLimit: 20
            $enableCache: false

    AppBundle\Validator\Constraints\ConstraintRssValidator:
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }

    # external service
    imgur.client:
        class: Imgur\Client
        calls:
            - [ setOption, [ 'client_id', "%imgur.client_id%" ] ]
            - [ setOption, [ 'client_secret', "%imgur.client_secret%" ] ]

    graby:
        class: Graby\Graby
        arguments:
            -
                error_message: false
                extractor:
                    config_builder:
                        site_config:
                            - "%kernel.root_dir%/site_config"
        calls:
            - [ setLogger, [ "@logger" ] ]
        tags:
            - { name: monolog.logger, channel: graby }

    graby.log_handler:
        class: Graby\Monolog\Handler\GrabyHandler

    Graby\Monolog\Handler\GrabyHandler:
        alias: graby.log_handler

    twitter.client:
        class: TwitterOAuth\TwitterOAuth
        arguments:
            -
                consumer_key: "%twitter.consumer_key%"
                consumer_secret: "%twitter.consumer_secret%"
                oauth_token: "%twitter.access_token%"
                oauth_token_secret: "%twitter.access_token_secret%"
                output_format: 'array'

    # custom formatter for import commande (below)
    monolog.import.formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments:
            - "[%%datetime%%] %%start_tag%%%%message%%%%end_tag%% %%context%% %%extra%%\n"

    Http\Client\Common\HttpMethodsClientInterface: '@httplug.client.default.http_methods'

    # alias to service from their class name
    Swarrot\SwarrotBundle\Broker\Publisher:
        alias: swarrot.publisher

    content_extractor:
        class: AppBundle\Content\Extractor
        arguments:
            - "@feed.extractor.chain"
            - "@feed.improver.chain"
            - "@feed.converter.chain"
            - "@feed.parser.chain"

    simple_pie_proxy:
        class: AppBundle\Xml\SimplePieProxy
        arguments:
            - "%kernel.root_dir%/cache/simplepie/"
            - 20
            - false

    xml_render:
        class: AppBundle\Xml\Render
        arguments:
            - "%domain%"

    # validator
    validator.rss.valid_rss:
        class: AppBundle\Validator\Constraints\ConstraintRssValidator
        arguments:
            - "@httplug.client.default.http_methods"
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }
